<?php
$trx_product_categories = [
    'all' => 'All Products',
    'devices' => 'Health Devices',
    'home-care' => 'Home Care',
    'supplies' => 'Medical Supplies',
    'wellness' => 'Wellness',
];

$trx_products = [
    'digital-bp-machine' => [
        'id' => 'digital-bp-machine',
        'name' => 'Digital BP Machine',
        'category' => 'devices',
        'icon' => 'BP',
        'price' => 2400,
        'sale_price' => 2200,
        'stock' => 'In Stock',
        'image' => 'assets/products/Digital BP Machine.png',
        'short' => 'Easy blood pressure monitoring device for home use.',
        'description' => 'A simple digital blood pressure monitor for regular home monitoring. Suitable for adults who need quick BP checks at home.',
        'features' => [
            'Easy one-touch operation',
            'Large digital display',
            'Suitable for home health monitoring',
            'Useful for elderly and chronic care users',
        ],
        'usage' => 'Sit calmly for 5 minutes, place the cuff correctly, and take the reading. Share abnormal readings with a doctor.',
    ],
    'glucometer-kit' => [
        'id' => 'glucometer-kit',
        'name' => 'Glucometer Starter Kit',
        'category' => 'devices',
        'icon' => 'G',
        'price' => 1850,
        'sale_price' => 1650,
        'stock' => 'In Stock',
        'image' => 'assets/products/Glucometer Starter Kit.png',
        'short' => 'Blood glucose monitoring kit for diabetic patients.',
        'description' => 'A practical glucose monitoring kit for regular blood sugar checks at home. Good for diabetic patients and family caregivers.',
        'features' => [
            'Quick glucose reading',
            'Portable and easy to use',
            'Useful for regular diabetic monitoring',
            'Suitable for home and travel',
        ],
        'usage' => 'Wash hands, use a new lancet and strip, then follow the device instruction. Keep a record of readings for doctor review.',
    ],
    'pulse-oximeter' => [
        'id' => 'pulse-oximeter',
        'name' => 'Pulse Oximeter',
        'category' => 'devices',
        'icon' => 'O₂',
        'price' => 1250,
        'sale_price' => 1050,
        'stock' => 'In Stock',
        'image' => 'assets/products/Pulse Oximeter.png',
        'short' => 'Finger pulse oximeter for SpO₂ and pulse monitoring.',
        'description' => 'A compact oximeter for checking oxygen saturation and pulse rate. Useful for respiratory monitoring and basic home care.',
        'features' => [
            'Checks SpO₂ and pulse rate',
            'Small and portable',
            'Fast result display',
            'Good for home monitoring',
        ],
        'usage' => 'Place on finger and wait for a stable reading. Seek medical advice if oxygen level stays unusually low.',
    ],
    'infrared-thermometer' => [
        'id' => 'infrared-thermometer',
        'name' => 'Infrared Thermometer',
        'category' => 'devices',
        'icon' => '°C',
        'price' => 1450,
        'sale_price' => 1250,
        'stock' => 'In Stock',
        'image' => 'assets/products/Infrared Thermometer.png',
        'short' => 'Contactless thermometer for fast temperature check.',
        'description' => 'A contactless infrared thermometer for quick temperature screening. Suitable for home, clinic, office and care settings.',
        'features' => [
            'Contactless temperature measurement',
            'Fast reading',
            'Simple display',
            'Useful for children and elderly users',
        ],
        'usage' => 'Hold at the recommended distance from forehead and press measure. Repeat if reading seems unusual.',
    ],
    'portable-nebulizer' => [
        'id' => 'portable-nebulizer',
        'name' => 'Portable Nebulizer',
        'category' => 'home-care',
        'icon' => 'N',
        'price' => 3200,
        'sale_price' => 2850,
        'stock' => 'In Stock',
        'image' => '',
        'short' => 'Nebulizer support for respiratory medication delivery.',
        'description' => 'A portable nebulizer for prescribed respiratory medicine delivery at home. Useful for asthma, COPD and breathing support under medical advice.',
        'features' => [
            'Portable home-care device',
            'Good for respiratory support',
            'Easy cleaning and handling',
            'Suitable for family use',
        ],
        'usage' => 'Use only with medicine prescribed by a doctor. Clean the mask and chamber properly after use.',
    ],
    'first-aid-box' => [
        'id' => 'first-aid-box',
        'name' => 'First Aid Box',
        'category' => 'supplies',
        'icon' => '+',
        'price' => 950,
        'sale_price' => 850,
        'stock' => 'In Stock',
        'image' => '',
        'short' => 'Basic first aid kit for home and office use.',
        'description' => 'A basic first aid box with essential items for minor cuts, dressing and immediate support before medical consultation.',
        'features' => [
            'Useful for home and workplace',
            'Basic wound-care support',
            'Compact and easy to store',
            'Good emergency preparation item',
        ],
        'usage' => 'Use for minor first aid only. For serious injury, bleeding or infection risk, contact a doctor or emergency service.',
    ],
    'adult-diaper-pack' => [
        'id' => 'adult-diaper-pack',
        'name' => 'Adult Diaper Pack',
        'category' => 'home-care',
        'icon' => 'AD',
        'price' => 1100,
        'sale_price' => 990,
        'stock' => 'In Stock',
        'image' => '',
        'short' => 'Comfortable adult diaper pack for elderly care support.',
        'description' => 'Adult diaper support for elderly patients, bed-ridden patients and home care needs. Size and availability can be confirmed before order.',
        'features' => [
            'Useful for elderly care',
            'Good for home nursing support',
            'Comfort-focused daily use item',
            'Size confirmation available by phone',
        ],
        'usage' => 'Change regularly and maintain hygiene. Consult a caregiver or doctor if skin irritation occurs.',
    ],
    'medicine-organizer' => [
        'id' => 'medicine-organizer',
        'name' => 'Medicine Organizer',
        'category' => 'wellness',
        'icon' => 'Rx',
        'price' => 650,
        'sale_price' => 550,
        'stock' => 'In Stock',
        'image' => '',
        'short' => 'Daily medicine organizer for better medication routine.',
        'description' => 'A simple medicine organizer to help users follow daily medication schedules. Useful for elderly patients and chronic care users.',
        'features' => [
            'Helps organize daily medicine',
            'Good for elderly users',
            'Portable and easy to carry',
            'Useful for chronic patient routines',
        ],
        'usage' => 'Fill according to the prescription schedule. Do not change medicine timing without doctor advice.',
    ],
];
?>
